	<META NAME="author" CONTENT="Ron Gallant, Chizeled Light, Gallant Web Design">
	<META NAME="description" CONTENT="Free Graphics, Animation, Links, and even a little something about Ron.">
	<META NAME="keywords" CONTENT="Ron's Place!, Ron's Place, Ron, ron, Ronald, ronald, Gallant, gallant, galant, hache, 
	french, France, geneology, Judo, judo, martial arts, Pink Floyd, Stephenville, stephenville, stevenville, s'ville, St. Georges, Newfoundland, 
	newfoundland, Terra Nova, terra nova, nf, NFLD, Canada, canada, Corner Brook, corner brook, St. John's, st. john's, St. Johns, Saint Johns, 
	St. John, Kilbride, kilbride, home page, web, www, design, advertise, advertisment, advertising, graphic, graphics, Photoshop, photoshop, 
	illustrator, free fonts, fonts, pictures, pics, photos, Anime, anime, japanamation, manga, draw, Free Graphics, themes, J.R.R. Tolkien, 
	tolkien, Lord of the Rings, LOTR, The Hobbit, hobbit, knife, knives, pink floyd, Pink Floyd, floyd, Dragon, dragon, dragons">
	<link href="assets/styles/main_style.css" rel="stylesheet" type="text/css" />
	
	<SCRIPT LANGUAGE="JavaScript">
	<!-- Copyright 1999 Lori Barrett and Ron Gallant
		function popupPage(page, l, t, w, h) {
			var windowprops = "location=no,scrollbars=yes,menubars=no,toolbars=no,resizable=yes" + ",left=" + l + ",top=" + t + ",width=" + w + ",height=" + h;
			var URL = page;
			popup = window.open(URL,"MenuPopup",windowprops);
		}
	// -->
	</SCRIPT>
</head>
<BODY BACKGROUND="assets/images/bg.jpg" TEXT="White" BGCOLOR="#442D0D" LINK="Yellow" VLINK="Yellow" ALINK="Red" onLoad="window.defaultStatus='Welcome to Ron&acute;s Place!';" onUnload="window.defaultStatus=''">
	<DIV ALIGN="center"><TABLE CELLPADDING="0" CELLSPACING="0" BORDER="0" WIDTH="500"><TR><TD>