<TABLE CELLPADDING="0" CELLSPACING="0" BORDER="0" WIDTH="100%">
	<TR>
		<TD ALIGN="LEFT" WIDTH="30%">
		<A HREF="index.php" TARGET="_top"><IMG  SRC="assets/images/back.gif" WIDTH=53 HEIGHT=53 ALT="Back" BORDER="0"></A>
			<A HREF="index.php" TARGET="_top"><IMG  SRC="assets/images/home.gif" WIDTH=53 HEIGHT=53 ALT="Home" BORDER="0"></A>
				<A HREF="/web/20010309221721/http://chizeledlight.com/index.php"><IMG  SRC="assets/images/next.gif" WIDTH=53 HEIGHT=53 ALT="Next" BORDER="0"></A></TD>
		<TD ALIGN="center" VALIGN="baseline" WIDTH="40%">
			<SCRIPT LANGUAGE="JavaScript" TYPE="text/javascript">
			<!--
				function map1(){
					if (document.selecter1.select1.options[document.selecter1.select1.selectedIndex].value != "none")
						{location = document.selecter1.select1.options[document.selecter1.select1.selectedIndex].value
						}
				}
			//-->
			</SCRIPT>
			<FORM NAME="selecter1">
				<SELECT NAME="select1" STYLE="font-family:Comic Sans MS; font-size=15px; background:beige">
					<OPTION VALUE="none" SELECTED>SHORT CUTS
					<OPTION VALUE="/artwork.php">---------MY ART
					<OPTION VALUE="/artwork.php">-&nbsp;Free Page Graphics
					<OPTION VALUE="/banners.php">-&nbsp;Banners
					<OPTION VALUE="/info.php">---------ABOUT ME
					<OPTION VALUE="/resume.php">-&nbsp;My Resume
					<OPTION VALUE="/morepages.php">---------LINKS
					<OPTION VALUE="/friends.php">-&nbsp;Link Page
					<OPTION VALUE="/tolkien.php">-&nbsp;J.R.R. Tolkien
					<OPTION VALUE="/pink_floyd.php">-&nbsp;Pink Floyd
					<OPTION VALUE="/knives.php">-&nbsp;Art knives
					<OPTION VALUE="/webpanel.php">---------FEEDBACK
					<OPTION VALUE="/webpanel.php">-&nbsp;Email Me
					<OPTION VALUE="/vbpro/htdocs/guestbook/index.html">-&nbsp;Sign Guestbook
					<OPTION VALUE="/vbpro/htdocs/guestbook/entries.html">-&nbsp;View Guestbook
					<OPTION VALUE="/vbpro/htdocs/guestbook/archive.html">-&nbsp;Guestbook Archives
				</SELECT>
				<INPUT TYPE="Button" VALUE="GO" ONCLICK="map1()" ALIGN="absbottom">
			</FORM></DIV></TD>
		<TD ALIGN="RIGHT" WIDTH="30%">
			<A HREF="guestbook/index.html"><IMG SRC="assets/images/sign.gif" BORDER="0" ALT="Sign"></A><A HREF="guestbook/entries.html"><IMG SRC="assets/images/view.gif" BORDER="0" ALT="View"></A></TD>
	</TR>
</TABLE>